### ISSUE TITLE
OSError: [Errno 8] Exec format error: '/startalk/download/qtalk_search/search.py'

### ISSUE THREAD

**Issue by arsenalpoll** [qunarcorp/qtalk_search#1]
```
$sudo python3.6 search.py


2019-04-16 22:50:24 - search.py[line:22] - INFO - CKEY AUTHORIZATION INITIALING...
 * Serving Flask app "search" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "search.py", line 156, in <module>
    app.run(host=service_host, port=service_port, debug=True)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/python3.6/site-packages/werkzeug/serving.py", line 988, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/lib/python3.6/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/usr/lib/python3.6/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/lib64/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/startalk/download/qtalk_search/search.py'
```

**Comment by arsenalpoll** [comment]
启动报错了。。

**Comment by gtouchgogo** [comment]
Looks like it's a problem brought by a conflict with system-wide python's werkzeug module, please try use virtualenv in the README to manage python's version control. 
Without guarantee and not recommend, you can do the following to update your system werkzeug :
# pip3 uninstall werkzeug
# pip3 install werkzeug==0.15.2
and then restart search service
---------
可能是因为你用的是系统级别的python 而服务依赖的werkzeug库和系统的有冲突 建议用virtualenv来管理python版本，以免和系统的python3引起冲突
